# Generated by Django 5.1.6 on 2025-02-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_networknode_level_alter_networknode_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
