# Generated by Django 5.1.6 on 2025-02-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_networknode_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networknode',
            options={'verbose_name': 'Сетевой узел', 'verbose_name_plural': 'Сетевые узлы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='networknode',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Розничная сеть'), (2, 'ИП')], default=0, editable=False, verbose_name='Уровень поставщика'),
        ),
    ]
